### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by stasink** [null93/milk-cookie-manager#43]
Are you planning to localize the extension?  In particular, the Russian language.

**Comment by null93** [comment]
It was actually on my to-do list. I would love to do that some time soon. My Russian is probably only good for speaking and probably grammatically incorrect. I would love some help on that part when it comes to it. Currently my life is a bit hectic and I do not have any free time to work on this. I'll update this issue when things start to get moving again. Until then PRs are always welcome 🙂.

**Comment by stasink** [comment]
In any case, you can count on me. I will provide you with a grammatically correct translation into Russian as soon as the localization file appears. I will follow the topic.

**Comment by null93** [comment]
@stasink Years later and a couple kids later, I finally got some time to work on this issue lol. If you are still interested I added the localization file in the "next" branch. You can find it [here](https://github.com/null93/milk-cookie-manager/blob/next/static/_locales/ru/messages.json). I decided not to translate everything since some of the technical stuff might get lost in translation.

If you do not wanna do it, I totally understand :)
