### ISSUE TITLE
Feature Request: Whitelist Or Blacklist

### ISSUE THREAD

**Issue by procoolheat** [null93/milk-cookie-manager#49]
It doesn't seem to work this way but if this was able to block all cookies by default and allow on a case by case basis it would be great for the average user.

I don't see anything in the options to set it up this way but maybe I missed it.  To allow by default and block each and every cookie on every site one goes is pretty time consuming.

**Comment by null93** [comment]
Hey! Thanks for using the extension and writing in! This extension indeed does not offer that feature but it is something I will consider next time I get a chance to work on an update. I will post any updates about the matter here.

**Comment by null93** [comment]
Sorry for the VERY long time between responses. I just got some time to work on this project again and I have decided that this is not a feature that I will be working on. Mainly because of the time it will take me to implement this.

That being said, if you decide to do this, I will always be open to reconsidering given you open a PR :)

Hope you understand, best of luck.
