### ISSUE TITLE
Import cookies doesn't work

### ISSUE THREAD

**Issue by Ronln** [null93/milk-cookie-manager#52]
I'm trying import to Chrome, Json is ok but It's always Failed To Import

**Comment by MDJonas** [comment]
I just installed Milk on the Brave browser (Mac, Catalina).  How do I import my whitelisted cookies from Firefox?  How do I find the JSON file fore Firefox's cookies?  

I'm glad to make a contribution if I can figure out how to fully use this extension.  Thank you.

**Comment by null93** [comment]
Hey! We do not support brave, but it should still work. 

First make sure you are not filtering by the active tab. This will show all the cookies in the browser.

<img width="561" alt="Screen Shot 2022-04-12 at 9 24 07 PM" src="https://user-images.githubusercontent.com/5500199/163087290-cbf6f941-51f2-4380-b22e-ef4c81f27aec.png">

Then you can export all your cookies by clicking on the export button and similarly import them in the other browser using the menu item right above.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/5500199/163087280-23409973-dea1-4de5-ab4d-d889fc0bc27e.png">

If that doesn't work you might have to omit the cookie store id since Brave might use a different cookie store key by default.

Hope that helps! Closing for now.
