### ISSUE TITLE
Trouble Importing Cookies and Feature Request

### ISSUE THREAD

**Issue by OllyHill** [null93/milk-cookie-manager#55]
Thank you mate for a lovely extension especially the GUI.

I have a problem and feature request.
REQUEST: Would it be possible to export all cookies at once instead of going to each individual website?

PROBLEM: I am unable to successfully authenticate to home.nest.com with cookies that are imported. The cookies are exported correctly and the import process is also successful, but I am prompted to login when going to home.nest.com. The method I logged into this domain originally is to use the "Login with Google Account" feature. This brings a popup box where I select my google account and am authenticated. But exporting and importing these cookies into a new chrome profile does not authenticate me. I did this on the same system in the same location so the environment is exactly the same, except the import is in a new Chrome profile.

Thanks again for a stupendous extension. Please drop a line if you can help.

Cheers,
Olly

**Comment by null93** [comment]
> Thank you mate for a lovely extension especially the GUI.

Thanks! I am really happy to hear that you like it. That is actually the reason I created this extension. It seemed like every other cookie manager looked outdated.

> REQUEST: Would it be possible to export all cookies at once instead of going to each individual website?

You can actually already do this by clicking on the filter button to show all cookies and then export as usual:

<img width="577" alt="Screen Shot 2022-03-01 at 2 18 08 PM" src="https://user-images.githubusercontent.com/5500199/156242592-e89d217c-459a-48c1-b57e-360ebe40601f.png">

> PROBLEM: I am unable to successfully authenticate to home.nest.com with cookies that are imported. The cookies are exported correctly and the import process is also successful, but I am prompted to login when going to home.nest.com. The method I logged into this domain originally is to use the "Login with Google Account" feature. This brings a popup box where I select my google account and am authenticated. But exporting and importing these cookies into a new chrome profile does not authenticate me. I did this on the same system in the same location so the environment is exactly the same, except the import is in a new Chrome profile.

I would first try to export the cookies, delete them, and then import them all in the same Chrome profile. This way you will know if its cookie related. It might just be Google doing some additional fingerprinting.

Hope that helps! Please consider rating or leaving a review on the Chrome WebStore :) Thanks!

**Comment by OllyHill** [comment]
> Thanks! I am really happy to hear that you like it. That is actually the reason I created this extension. It seemed like every other cookie manager looked outdated.
> 
I'm with you mate. Most extensions that transfer cookies are functional, but lack chops in the visual department.

> You can actually already do this by clicking on the filter button to show all cookies and then export as usual:
> 
Lovely. Thank you for the tip.

> I would first try to export the cookies, delete them, and then import them all in the same Chrome profile. This way you will know if its cookie related. It might just be Google doing some additional fingerprinting.
>
Thank you for the tip. I found something very interesting while trying to re-import into the same profile. I backed up cookies from home.nest.com and then deleted these cookies (8 listed in Chrome Settings). I went back to home.nest.com to confirm I was no longer logged in, but to my surprise I was logged right back in. Buggar. I fired up Dev Tools and inspected cookies. The two domains listed are "home.nest.com" and "accounts.google.com" so I assume accounts.google.com is responsible for logged me in. This makes sense since I used Google Sign-In to authenticate. I logged back in to home.nest.com using the google sign-in method again. This time, I backed up the cookies of home.nest.com and accounts.google.com. I then deleted these cookies and in fact, I was no longer logged into home.nest.com which tells me it's the cookies from accounts.google.com that are important for authentication. But mate, when I reimported both cookie files, I was not authenticated. My brain was flying, but have a few questions if you don't mind:

1) Even though it would not work in this case, but why doesn't the extension export cookies from accounts.google.com since it's important for this website to function?
2) As a quick test, I dumped all cookies and reimported into the new profile. I still was not authenticated to home.nest.com. 

Just wondering what you thought mate. It's not a big deal in the end, but want to make sure when I transfer profiles (as I occasionally do), everything is gonna work.  

> Hope that helps! Please consider rating or leaving a review on the Chrome WebStore :) Thanks!
>
Done. Just wrote a review.

**Comment by null93** [comment]
> Done. Just wrote a review.

Thank you very much! You left a very kind review! 🙂 🎉

> Even though it would not work in this case, but why doesn't the extension export cookies from accounts.google.com since it's important for this website to function?

The reason it doesn't is more to do with how the OAUTH2 request flow works. When you choose to login with your google account, you are redirected to a google which is allowed to set cookies for the google domain name and manage your logged in session (separate from home.nest.com).

The reason we don't show cookies for other domains like that is because those connections are very ambiguous. Think about it this way, if a webpage links to an image from another domain name, there is an HTTP request that is created to fetch that image and in turn an HTTP response that is going to be returned potentially with the **Cookies** header being filled out (this means that cookies will be set for that image src's domain name).

Furthermore, it might not be useful especially considering that the client side javascript or server side code does not have access to cookies from another root domain name.

> As a quick test, I dumped all cookies and reimported into the new profile. I still was not authenticated to home.nest.com.

I am honestly unsure of this one. Theoretically, this should be just fine since cookies just serve as a mechanism to save stateful information. For example, I exported all my cookies for my profile, deleted them, and reimported them and I am still logged into google and everything else.

Perhaps they are doing some other fingerprinting to prevent cookie-jacking? Either way, I wish you the best of luck and hope you find a solution to this! I will close this issue for now, but feel free to reopen it if you think it needs to be :)
