### ISSUE TITLE
Cookie import from .json fails

### ISSUE THREAD

**Issue by furryalpacca** [null93/milk-cookie-manager#58]
Been using cookies from another browser. I have formatted the cookies from netscape to json but in milk they get flagged as failed. Does milk not read json correctly?

**Comment by null93** [comment]
Hey! Not sure what other browser you are using but support chrome. A lot of times the default store id of the browser is different. In chrome the default store id is `0`. What do you cookies look like? Here is an example of the format:

```
[
	{
		"domain": ".github.com",
		"expirationDate": 1677686883.743482,
		"hostOnly": false,
		"httpOnly": false,
		"name": "_octo",
		"path": "/",
		"sameSite": "lax",
		"secure": true,
		"session": false,
		"storeId": "0",
		"value": "FOO"
	}
]
```

**Comment by furryalpacca** [comment]
Apologies for raising an issue, I figured out it was an issue with my json converter, boolean flags were beeing set to True/False instead of true/false. I do however have a rather specific request for the project I am working on & my JS is too bad to mod your extension by myself :/ I'd like to create the file input element before clicking the import button and then use the button to process the file. A textarea (or silimilar) would do too, I am trying to automate the use of the extension and handleing OS file selectors is kind of a cheap workaround! I would really appreciate if you could help me out here, I do understand if you are too busy. Sorry again for raising an issue

**Comment by null93** [comment]
Glad to hear you figured it out!

I definitely am really busy at the moment but I would like to help by pointing out how I've done it and maybe it will help you.

You can find where I actually set the cookie here: https://github.com/null93/milk-cookie-manager/blob/master/src/utils/cookie.js#L26. It is simply using Chrome's api to set the cookie value, checkout https://developer.chrome.com/docs/extensions/reference/cookies/#method-set for more details. In my example I use "browser" instead of "chrome" for cross-compatibility (polyfill). You can only run this code in the context of an extension that requested the "cookies" permission.

I am not exactly sure how you are going about implementing your workaround, but I hope that helps. I am gonna close the issue for now, but if you want to ask me anything further, please feel free to re-open it :)

Best of luck!
