### ISSUE TITLE
Feature Request: Recall Recently Used Search

### ISSUE THREAD

**Issue by cdjohnson** [null93/milk-cookie-manager#80]
**Use Case:**

I have a set of web sites I communicate with that uses various levels of SSO (SAML, OIDC, etc) that all attempt to timeout my connection after various intervals (hours, days, etc).  They freqently get confused and out of sync (likely a bug in the web site) that  ultimately requires me to delete a set of well-known cookies (5 of them) to trigger a full re-authentication.

To use Milk, I perform the following actions:
1.  Open an empty tab
2. Find the regex in my notes.
3. Paste my regex into the Milksearch tab
4. Delete all filtered cookies.

I would love it if I could perform the following:
1. Have it memorize the latest search string I used, so I don't have to paste in my string from my notepad every time.
2. (bonus) Have it memorize the last N searches and select which one to use

The actions would become:
1.  Open an empty tab
2. Recall the latest regex in Milk (or select a recent one)
3. Delete all filtered cookies.

**Comment by null93** [comment]
Hey @cdjohnson,

I think an option to remember last search is a reasonable request and is something that I can implement. Having a history of searches doesn't seem like something that would fit since it filters the results on every keystroke.

I don't have a timeline for you, but I will probably fit this into the next release.

Site Note: Are you opening a new tab in order to search all cookies? If so, toggling the following should give you the same results:

<img width="226" alt="Screenshot 2024-11-08 at 10 31 55 PM" src="https://github.com/user-attachments/assets/b80a1abe-7bcd-4941-9334-66ca30c43257">
